//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1.Data_
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhones
    {
        public int PhoneID { get; set; }
        public int UserID { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
